### ISSUE TITLE
Move components to descripto-wallet

### ISSUE THREAD

**Issue by dr-orlovsky** [mycitadel/mycitadel-desktop#16]
- [ ] PSBT composition
- [ ] `Prevout` type
- [ ] Electrum types (`UtxoTxid` etc)
- [ ] Coin-selection algorithms
- [ ] PSBT fee computation
- [ ] WalletCore type and wallet ids
- [ ] PSBT meta-data proprietary fields (name, description etc)
