### ISSUE TITLE
Release v1

### ISSUE THREAD

**Issue by dr-orlovsky** [mycitadel/mycitadel-desktop#17]
# Screens

No | Window | Screen | Complete | Debugged
--:| -------- | ------- |:-------:|:----------:
1 | About | | ✅ | ✅ 
2 | Launcher | New | ✅ | ✅
3 | Launcher | Open | ✅ | ✅
4 | Launcher | Import | n/a | n/a
5 | Settings | Signers | ✅ | ✅
6 | Settings | Signers / Device | ✅ | ✅ 
7 | Settings | Signers / Add xpub | ✅ | ✅
8 | Settings | Spending conditions | ✅ | ✅
9 | Settings | Descriptor | ✅ | ✅
10 | Settings | Network | ✅ | ✅
11 | Wallet | Generic | ✅ | ✅
12 | Wallet | History | ✅ | ✅
13 | Wallet | Coins | ✅ | ✅
14 | Wallet | Addresses | ✅ | ✅
15 | Wallet | Invoice | ✅ | ✅
16 | Payment | | ✅ | ✅
17 | PSBT | Generic | ✅ | ✅
18 | PSBT | Sign | ✅ | ✅

# Business Logic

No | Funcionality | Complete | Debugged
--:| -------- |:-------:|:----------:
1 | Wallet file save/open | ✅ | ✅
2 | Wallet templates | ✅ | ✅
3 | Electrum server connectivity management | ✅ | ✅
4 | Wallet electrum sync | ✅ | ✅
6 | Hardware signers discovery | ✅ | ✅
7 | Hardware signers signatures | ✅ | ✅
8 | Spending conditions & descriptor construction | ✅ | ✅
9 | PSBT construction | ✅ | ✅
10 | PSBT analysis for signing | ✅ | ✅
11 | Window management | ✅ | ✅

# Debugging user stories

## Constructing new wallet
- [x] Devices import mainnet keys even on testnet
- [x] Mainnet selection does not pass to settings dialog
- [x] Settings dialog keeps last xpub selection details on new wallet init
- [x] Invalid child number in key origin
- [x] Single-sig still allows editing spending conditions (macOS)
- [x] Import key buttons are not disabled when an xpub present in single-sig
- [x] Origin editor disabled for imported xpubs
- [x] Edited key origin does not get into the descriptor
- [x] Origin fingerprint can't be edited for custom xpubs with depth > 1
- [x] Imported xpubs are not prefixed with 'm' on origin info
- [x] Use taproot flag in launcher window is not passed to settings dialog
- [x] Xpub type is not matched against wallet format in xpub_dlg (tested for Zpub in single-sigs)
- [x] Same xpub can be added multiple times
- [x] Multisig wallet (org/corp template) containing many xpub still produces single-sig descriptor
- [x] Unclear error message for n-of-m multisigs where n>m
- [x] 1-of-m multisig spending condition is not processed
- [x] ~~Errors related to xpubs are shown only when the xpub is selected~~ feature, not bug
- [x] Segwit multisig with two and more spending conditions produces duplicate keys error
- [x] Adding second condition to taproot multisig crashes the app
- [x] n-of-m segwit wallets using `multi` instead of `sortedmulti` descriptor
- [x] New multisig templates default importing devices to single-sig schema
- [x] Signer name for newly added devices is not editable
- [x] Device name for newly added devices is not displayed in the details section

## Wallet operations
- [x] Opening wrong files crashes the app
- [x] Balances in history are not read
- [x] Last change index is not updated
- [x] List of addresses do not show change addresses
- [x] Number of transactions for addresses are multiplied by two
- [x] Addresses do not show derivation indexes
- [x] Editing wallet settings show different spending conditions and descriptor
- [x] Add launcher menu item to hamburger menu

## Payment
- [x] Selecting fee rate from menu does not update the actual rate
- [x] Subsatoshi amount incorrectly detected (due to float bug?)
- [x] Min fee limit is not checked

## Signing psbt
- [x] Number of required signatures is incorrect
- [x] Signer master fp is zeroed
- [x] Signer index starts from 0
- [x] Account key is not detected
- [x] Add ".psbt" extension when saving psbt
- [x] Update window title after saving psbt
- [x] Rename "Save" into "Save As"
- [x] Disable "Save" button when there is nothing to save
- [x] Disable "Broadcast" button after tx broadcasting
- [x] After signing list of signers sometimes gets duplicated
- [x] For multiple-input txes number of signers is multiplied
- [x] Signer names are not preserved
