### ISSUE TITLE
Feature ideas (brainstorming)

### ISSUE THREAD

**Issue by dr-orlovsky** [mycitadel/mycitadel-desktop#20]
## New screens
- [ ] Signer/device organizer
- [ ] View operation history details (extended transaction information)
- [ ] Detailed address information
- [ ] Detailed UTXO information
- [ ] Blockchain explorer (blocks, transactions, addresses)
- [ ] Arbitrary tx viewer (from/to file)
- [ ] Blockchain information
- [ ] App-wide settings (exchange, fiat, Tor, local storage)
- [ ] WIP transactions page (in wallet)
- [ ] Contacts/counterparties page (in wallet)

## New features
- [x] Copy existing wallet core to the newly created wallet such that spending conditions and signers can be edited
- [ ] Support spending requirement for a specific signature
