### ISSUE TITLE
Distributives & installers

### ISSUE THREAD

**Issue by dr-orlovsky** [mycitadel/mycitadel-desktop#68]
This is an issue tracking ongoing work on providing more user-friendly distributives and installation options on different platforms.

- [x] Write installation instructions ([written](../doc/INSTALL.md))

# Linux

- [x] Debian package
    - [ ] Publish to some repository / create & maintain some repository
    - [ ] Find a way to add automatic `hwi` installation
- [x] Flatpak
    - [ ] Publish to flathub
- [ ] Snapcraft
    - [ ] Publish to SnapStore
- [ ] AppImage

# macOS

We can't get to AppStore with GTK version, however pay attention that a separate native MyCitadel application (made with SwiftUI) for all Apple platforms [exists](https://github.com/mycitadel/mycitadel-apple) which can be run on macOS and is planned to be published to Mac App Store. Right now it is outdated, but we are working on the new version.

- [ ] Brew formula & add to brew repository
    - [ ] Do `hwi` brew formula and use it as a dependency
- [ ] SnapStore (one day when it will be working)

# Windows 10 and 11 

- [ ] MSI installer
- [ ] Windows (App) Store
- [ ] Some package manager? Choco? Winget? Have no experience here, any help is welcome.

No support is planed for versions before Win10.

# Cross-platform source code

(Not user-friendly)

- [x] Nix pack for Linux & macOS
    haven't yet worked with it, so need @dpc and @NCrashed help to understand where we are at after their PRs got merged:
    - https://github.com/mycitadel/mycitadel-desktop/pull/36
    - https://github.com/mycitadel/mycitadel-desktop/pull/41

- [x] Cargo: `cargo install mycitadel` and `git clone && cargo install --path .`
    provide desktop integration through `build.rs` script:
    * [ ] Debian
    * [ ] Non-debian Linux
    * [ ] macOS
    * [ ] Windows

- [x] Meson: `git clone && meson install`
    provide desktop integration
    * [ ] Debian
    * [ ] Non-debian Linux
    * [ ] macOS
    * [ ] Windows

**Comment by fczuardi** [comment]
`nix build` on the tip of master branch fails with this error:

```
error: builder for '/nix/store/n2ccqmhmic3ly875jgzwzmi9wdjv3grl-mycitadel-deps-1.3.0.drv' failed with exit code 101;
       last 10 log lines:
       > configuring
       > will append /build/dummy-src/.cargo-home/config.toml with contents of /nix/store/n874yvrhmdasskw7pll7xni82mqwi147-vendor-cargo-deps/config.toml
       > no configure script, doing nothing
       > setting CARGO_BUILD_RUSTFLAGS to "--remap-path-prefix /nix/store/n874yvrhmdasskw7pll7xni82mqwi147-vendor-cargo-deps=/sources"
       > building
       > cargo 1.60.0 (d1fd9fe 2022-03-01)
       > running: cargo check --workspace --release --all-targets
       > cargo build --workspace --release
       >
       > error: package `bitcoin_hd v0.10.0` cannot be built because it requires rustc 1.65.0 or newer, while the currently active rustc version is 1.60.0
       For full logs, run 'nix log /nix/store/n2ccqmhmic3ly875jgzwzmi9wdjv3grl-mycitadel-deps-1.3.0.drv'.
error: 1 dependencies of derivation '/nix/store/r0y9v4aib4mf2rn1vaxdf3zyqxi0zy1i-mycitadel-1.3.0.drv' failed to buil
```

changing [fenix-channel](https://github.com/mycitadel/mycitadel-desktop/blob/master/flake.nix#L33) from stable to latest dont work either (it uses 1.62.0, which is also not 1.65.0)

**Comment by fczuardi** [comment]
updating the flake.lock with a `nix flake update` fixed the error above, but then it misses a python3 interpreter to build:

```
$ nix build
warning: Git tree '/home/fcz/github/mycitadel-desktop' is dirty
error: builder for '/nix/store/c9v9badwkjfwnhvzkh9fa6m7c4jk0yhs-mycitadel-deps-1.3.0.drv' failed with exit code 101;
       last 10 log lines:
       >   --- stdout
       >   cargo:rerun-if-env-changed=PYO3_CONFIG_FILE
       >   cargo:rerun-if-env-changed=PYO3_PYTHON
       >   cargo:rerun-if-env-changed=VIRTUAL_ENV
       >   cargo:rerun-if-env-changed=CONDA_PREFIX
       >   cargo:rerun-if-env-changed=PATH
       >
       >   --- stderr
       >   error: no Python 3.x interpreter found
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/c9v9badwkjfwnhvzkh9fa6m7c4jk0yhs-mycitadel-deps-1.3.0.drv'.
error: 1 dependencies of derivation '/nix/store/sfg7ypjh3w90vajhzsqkf0k47f2hypbb-mycitadel-1.3.0.drv' failed to build

```

**Comment by fczuardi** [comment]
adding `pkgs.python311` to [this list](https://github.com/mycitadel/mycitadel-desktop/blob/master/flake.nix#L42) fixed the build!

I can open a PR with both updates...

**Comment by dr-orlovsky** [comment]
@fczuardi thank you for investigating and doing the PR! Replied you there
