### ISSUE TITLE
RGB support (initial)

### ISSUE THREAD

**Issue by dr-orlovsky** [mycitadel/mycitadel-desktop#70]
# UI

## Launcher
- [x] Disable unsupported templates when RGB support is selected

## Settings
- [x] Disable unsupported options / display alert for wrong descriptor if RGB is used

## Wallet
- [x] List of RGB assets (present only in RGB-enabled wallets)
- [x] Informational panel about the asset (ticker, name, contract id)
- [x] Import and remove buttons for assets
- [x] RGB-specific changes to the history and coins panels
- [ ] Invoicing
- [ ] Making payments
- [ ] Accepting consignments

# Integration

- [x] RGB-enabled descriptors
- [x] Build & link with rgb-contracts library
- [ ] Dedicated RGB thread with runtime

# Functions

- [ ] Import asset from a file
- [ ] Remove asset (if not owned by the local wallet)
- [ ] Display RGB asset balance
- [ ] RGB operation history
- [ ] RGB "coins" list (avaliable state on UTXOs)
- [ ] Invoicing
- [ ] Making payments
- [ ] Accepting consignments
