### ISSUE TITLE
RGB support (advanced)

### ISSUE THREAD

**Issue by dr-orlovsky** [mycitadel/mycitadel-desktop#71]
- [ ] Paste RGB contracts and consignments as BASE64 texts
- [ ] Support for invoice URLs
- [ ] Issue an asset in simple form
- [ ] Export contract
- [ ] Integration with rgbex.io contract lists (contract search, import etc)
- [ ] Detailed contract information popover
- [ ] Support for NFTs
- [ ] Checking contract published signatures
- [ ] Support for logo and metadata
