### ISSUE TITLE
Application-wide settings

### ISSUE THREAD

**Issue by dr-orlovsky** [mycitadel/mycitadel-desktop#77]
- [ ] Default electrum server
- [ ] Directory for stash
- [ ] Directory for cache
- [ ] (future) cloud settings
- [ ] Socks5 configuration
- [ ] HWI test
