### ISSUE TITLE
Exchange integration

### ISSUE THREAD

**Issue by dr-orlovsky** [mycitadel/mycitadel-desktop#81]
- [ ] Buy bitcoins with Bity
- [ ] Exchange RGB assets with colorshift
- [ ] Search and add contracts with rgbex
