### ISSUE TITLE
MyCitadel cloud integration for organizations (basics)

### ISSUE THREAD

**Issue by dr-orlovsky** [mycitadel/mycitadel-desktop#85]
# UI

- [ ] Cloud wallets tab in Launcher window

# Functionality

- [ ] App identity keys (for logging)
- [ ] Sync for annotations and PSBTs
- [ ] Wallet descriptor editing rights
- [ ] Wallet descriptor update synchronization
