### ISSUE TITLE
Feature roadmap

### ISSUE THREAD

**Issue by dr-orlovsky** [mycitadel/mycitadel-desktop#86]
The plan is subjected to many years of work and lists main development focus areas.

- Advanced scripting
   * [ ] Import arbitrary descriptors
   * [ ] MuSig2 support
   * [ ] Tapscript miniscript
   * [ ] New BP-style descriptors
   * [ ] Taprot "unspendable"
   * [ ] Tapret support (part of RGB)
- Cloud
   * [ ] Electrum cloud infrastructure
   * [ ] Subscriptions for private electrum and Bitcoin Core
   * [ ] Wallet synchronization
   * [ ] Wallet monitoring/alerting
- Professional accounting
   * [ ] Annotations
   * [ ] Export and accounting tool integration
   * [ ] Access rights
- Replace-by-fees
   * [ ] RBF support
   * [ ] Pre-signed cancel transactions
- Exchanges, explorers & registries
   * [x] Pricing feeds
   * [ ] Integration with exchanges (Bity, Colorshift)
   * [ ] Integration with rgbex.io contract registry
- Privacy
   * [ ] Mixnets
   * [ ] Bloom filters
   * [ ] Joinmarket?
- Other
   * [ ] Advanced coinselection
   * [ ] Convenants?

**Comment by sskras** [comment]
Hey, I haven't deeply investigated into the project yet. So please excuse me if my question sounds wrong:

is there any plans add support for other cryptocurrencies and tokens?  Probably by doing that in pluggable, not static way.

I guess that would require an additional UI changes.

**Comment by UkolovaOlga** [comment]
Hi @sskras.
No, we are not planning to support any other cryptocurrencies or tokens, except for the RGB-based ones.

**Comment by romancerny** [comment]
Hi, thanks for an excellent product. Are there rough date estimates for V2 (Basics of RGB support, UI overhaul) release? Or what would be the date estimates for features mentioned in issue #70 & #71? Thank you.

**Comment by dr-orlovsky** [comment]
We had to split the project in two: bitcoin-only version (based on the currently released) and RGB version (codenamed "MyRGB"). The reason for that was the fact that implementing complex multisigs (like at this moment we have in current MyCitadel) for RGB will require a plenty of work and not be usable to many people who just want to "play with RGB".

So, Bitcoin MyCitadel v2 will come with better HW wallet support and cross-wallet sync (PSBTs, comments on past transactions). ETA is this spring - after MyRGB (see below).

MyRGB v1, which is the thing we are focused on, will come ~two weeks after v0.11 version of RGB is released (expected next month)

**Comment by romancerny** [comment]
Thanks. That is a great news as I'm interested in RGB :-)

Is MyRGB a new public repo, or just a branch in MyCitadel? Can't seem to find it.
